config/routes.rb
Rails.application.routes.draw do
  resources :inquiries
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "inquiries#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  enum inquiry_type: { import: 0, export: 1 }

  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :inquiry_type, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  before_action :set_inquiry, only: %i[ show edit update destroy ]

  # GET /inquiries or /inquiries.json
  def index
    @inquiries = Inquiry.all.order(:updated_at)
  end

  # GET /inquiries/1 or /inquiries/1.json
  def show
    @next_inquiry_id = Inquiry.where("id > ?", @inquiry.id).order(:id).first
    @next_inquiry_id ||= Inquiry.first

    @prev_inquiry_id = Inquiry.where("id < ?", @inquiry.id).order(id: :desc).first
    @prev_inquiry_id ||= Inquiry.last
  end

  # GET /inquiries/new
  def new
    @inquiry = Inquiry.new
  end

  # GET /inquiries/1/edit
  def edit
  end

  # POST /inquiries or /inquiries.json
  def create
    @inquiry = Inquiry.new(inquiry_params)

    respond_to do |format|
      if @inquiry.save
        format.html { redirect_to inquiry_url(@inquiry), notice: "Inquiry was successfully created." }
        format.json { render :show, status: :created, location: @inquiry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inquiries/1 or /inquiries/1.json
  def update
    respond_to do |format|
      if @inquiry.update(inquiry_params)
        format.html { redirect_to inquiry_url(@inquiry), notice: "Inquiry was successfully updated." }
        format.json { render :show, status: :ok, location: @inquiry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inquiries/1 or /inquiries/1.json
  def destroy
    @inquiry.destroy!

    respond_to do |format|
      format.html { redirect_to inquiries_url, notice: "Inquiry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inquiry
      @inquiry = Inquiry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inquiry_params
      params.require(:inquiry).permit(:name, :email, :description, :budget, :inquiry_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/inquiries/_form.html.erb
<%= form_with(model: inquiry) do |form| %>
  <% if inquiry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inquiry.errors.count, "error") %> prohibited this inquiry from being saved:</h2>

      <ul>
        <% inquiry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container shadow-lg p-5 rounded">
    <div class="form-floating mb-3">
      <%= form.text_field :name, class:"form-control", placeholder:"name", autocomplete:"off" %>
      <%= form.label :name %>
    </div>
    <div class="form-floating mb-3">
      <%= form.text_field :email, class:"form-control", placeholder:"email", required: true, autocomplete:"off" %>
      <%= form.label :email %>
    </div>
    <div class="form-floating mb-3">
      <%= form.text_area :description, class:"form-control", placeholder:"desc", style: "height: 100px" %>
      <%= form.label :description %>
    </div>
    <div class="row">
      <div class="col">
        <div class="form-floating mb-3">
          <%= form.number_field :budget, class:"form-control", placeholder:"test", min: 0, max: 100000000 %>
          <%= form.label :budget %>
        </div>
      </div>
      <div class="col">
        <div class="form-floating mb-3">
          <%= form.select :inquiry_type, 
            Inquiry.inquiry_types.keys.map { |key| [key.humanize, key] }, 
            { prompt: "Select a type" }, 
            class: "form-select", required: true %>
          <%= form.label :inquiry_type, style: "display: block", class:"form-label" %>
        </div>
      </div>
    </div>

    <div class="text-center">
      <%= form.submit class:"btn btn-success" %>
    </div>
  </div>

<% end %>

app/views/inquiries/_inquiry.html.erb
<div id="<%= dom_id inquiry %>" class="container d-flex shadow rounded p-3 pt-4 mb-3 mt-2 position-relative">
  <div class="col-3">
    <%= inquiry.inquiry_type.upcase %>
  </div>

  <div class="col-3">
    <%= inquiry.name %>
  </div>

  <div class="col-3">
    $ <%= number_with_delimiter(inquiry.budget) %>
  </div>

  <div class="col-3">
    <%= time_ago_in_words(inquiry.created_at).capitalize %>
  </div>
    <a href=<%= inquiry_path(inquiry) %> class="position-absolute top-50 end-5 translate-middle">
      <i class="bi bi-three-dots"></i>
    </a>
  <%# <%= link_to "More", inquiry, class:"btn btn-outline-secondary position-absolute top-50 end-0 translate-middle rounded-pill" %> 
</div>

app/views/inquiries/edit.html.erb
<h1>Editing inquiry</h1>

<%= render "form", inquiry: @inquiry %>

<br>

<div>
  <%= link_to "Show this inquiry", @inquiry %> |
  <%= link_to "Back to inquiries", inquiries_path %>
</div>

app/views/inquiries/index.html.erb
<div class="container">
  <h1 class="mt-5 mb-5">Inquiry List</h1>

  <div id="inquiries" class="container">
    <div class="container d-flex shadow-sm rounded p-2 user-select-none">
      <strong class="col-3">Type</strong>
      <strong class="col-3">Name</strong>
      <strong class="col-3">Budget</strong>
      <strong class="col-3">Time since</strong>
    </div>
    <% @inquiries.each do |inquiry| %>
      <%= render inquiry %>
      
    <% end %>
  </div>

  <%= link_to "New inquiry", new_inquiry_path, class:"btn btn-outline-success mt-5" %>

</div>

app/views/inquiries/new.html.erb
<div class="container">
  <h1 class="mb-5 mt-5">New Inquiry</h1>
  <div class="container">
    <%= render "form", inquiry: @inquiry %>
  </div>
  <div class="mt-5">
    <%= link_to "Go to Inquiry List", inquiries_path, class:"btn btn-outline-secondary" %>
  </div>
</div>

app/views/inquiries/show.html.erb
<div class="container">
  <div class="container gx-5 mb-1" style="min-height: 300px; max-width: 500px;">
    <div class="row">
      <div class="col-1">
        <h2 class="text-center">
          <%= @inquiry.id %>
        </h2>
      </div>
      <div class="col-11">
        <h2>
          <%= @inquiry.inquiry_type.upcase %>
        </h2>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <h5>
          From: <%= @inquiry.name %> | <i><%= @inquiry.email %></i>
        </h5>
      </div>
      <div class="col-12">
        <h6>Description :</h6>
        <textarea class="form-control" type="text" style="max-width: 400px" disabled readonly><%= @inquiry.description %></textarea>
      </div>
      <div class="d-flex col-12">
        <h6>Budget :</h6>
        <h6 class="ms-1">
          $<%= number_with_delimiter(@inquiry.budget) %>
        </h6>
      </div>
    </div>
  </div>

  <div class="d-flex">
    <div class="col text-center mb-5">
      <%= link_to "Previous", inquiry_path(@prev_inquiry_id), class:"btn btn-outline-primary" %>
    </div>
    <div class="col text-center mb-5">
      <%= link_to "Next", inquiry_path(@next_inquiry_id), class:"btn btn-outline-primary" %>
    </div>
  </div>
 
 <div class="row mx-auto">
    <div class="col">
      <%= link_to "Back to inquiries", inquiries_path, class:"btn btn-outline-secondary" %>
    </div>
    <div class="col">
      <%= link_to "Edit this inquiry", edit_inquiry_path(@inquiry), class:"btn btn-outline-warning" %>
    </div>
    <div class="col">
      <%= button_to "Destroy this inquiry", @inquiry, method: :delete, class:"btn btn-outline-danger" %>
    </div>
  </div>
</div>

app/views/layouts/_alert.html.erb
<div class="toast-container">
    <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
        <strong class="me-auto">Notice</strong>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body">
        <%= notice %>
    </div>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand d-flex align-items-center" href=<%= root_path %>>
        <%= image_tag("Company_Logo-logoOnly-removebg.png", class: "d-inline-clock align-text-top", width: 50, height: 40) %>
        Inquiry Form
    </a>
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link active" href=<%= inquiries_path %>>List</a>
        </li>
        <li>
          <a class="nav-link" href=<%= new_inquiry_path %>>New</a>
        </li>
    </ul>
    <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search">
        <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InquiryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <style>
    .toast {
      position: fixed;
      left: 15%;
      transform: translateX(-50%);
    }
    .toast-container {
      position: fixed;
      top: 10px;
      left: 0;
      width: 100%;
      transform: translateY(-50%);
      z-index: 1050;
    }
  </style>
  </head>

  <body>
    <%= render partial: "layouts/navbar" %>
    <%= render partial: "layouts/alert" %>
    <main class="container">
      <%= yield %>
    </main>
    <script>
      var notice = '<%= notice %>'.trim();
      if (notice) {
        $('.toast .toast-body').text(notice);
        $('.toast').toast('show');
      }
    </script>
  </body>
</html>